run_analysis <- function(){
    library(data.table)
    library(dplyr)
    feature <- read.table("./UCI HAR Dataset/features.txt")
    subject.test <- read.table("./UCI HAR Dataset/test/subject_test.txt")
    x.test <- read.table("./UCI HAR Dataset/test/X_test.txt")
    y.test <- read.table("./UCI HAR Dataset/test/Y_test.txt")
    #body.acc.x.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt")
    #body.acc.y.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt")
    #body.acc.z.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt")
    #body.gyro.x.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt")
    #body.gyro.y.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt")
    #body.gyro.z.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt")
    #total.acc.x.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt")
    #total.acc.y.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt")
    #total.acc.z.test <- read.table("./UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt")
    testdt <- cbind(subject.test , y.test, x.test[,grep(".*[mM]ean.*|.*std.*" , feature[,2])])
    testdf <- as.data.frame(testdt)
    measure.name <- feature[grep(".*[mM]ean.*|.*[sS]td.*" , feature[,2]),2]
    cnames <- c("subject" , "labels" , as.character(measure.name) )
    #print(measure.name)
    #print(names(testdf))
    colnames(testdf) <- cnames
    #print(names(testdf))
    subject.train <- read.table("./UCI HAR Dataset/train/subject_train.txt")
    x.train <- read.table("./UCI HAR Dataset/train/X_train.txt")
    y.train <- read.table("./UCI HAR Dataset/train/Y_train.txt")
    #body.acc.x.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt")
    #body.acc.y.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt")
    #body.acc.z.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt")
    #body.gyro.x.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt")
    #body.gyro.y.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt")
    #body.gyro.z.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt")
    #total.acc.x.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt")
    #total.acc.y.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt")
    #total.acc.z.train <- read.table("./UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt")
    traindt <- cbind(subject.train , y.train, x.train[,grep(".*[mM]ean.*|.*std.*" , feature[,2])])
    traindf <- as.data.frame(traindt)
    colnames(traindf) <- cnames
    #print(names(traindf))
    complete <- rbind(testdf,traindf)
    #print(names(complete))
    #print(dim(complete))
    label <- as.character(complete[,2])
    activities <- gsub("1" , "WALKING" , label)
    activities <- gsub("2" , "WALKING_UPSTAIRS" , activities)
    activities <- gsub("3" , "WALKING_DOWNSTAIRS" , activities)
    activities <- gsub("4" , "SITTING" , activities)
    activities <- gsub("5" , "STANDING" , activities)
    activities <- gsub("6" , "LAYING" , activities)
    complete.activities <- data.frame(subject = complete[,1] , activities = activities , complete[,3:(ncol(complete))])
    #print(head(complete.activities))
    tidynames <- gsub("Acc" , "Accelerometer" , names(complete.activities))
    tidynames <- gsub("Gyro" , "Gyroscope" , tidynames)
    tidynames <- gsub("BodyBody" , "Body" , tidynames)
    tidynames <- gsub("Mag" , "Magnitude" , tidynames)
    tidynames <- gsub("^t" , "Time" , tidynames)
    tidynames <- gsub("^f" , "Frequency" , tidynames)
    tidynames <- gsub("tBody" , "TimeBody" , tidynames)
    tidynames <- gsub("-mean()" , "Mean" , tidynames)
    tidynames <- gsub("-std()" , "StandardDiviation" , tidynames)
    tidynames <- gsub("-freq()" , "Frequency" , tidynames)
    tidynames <- gsub("angle" , "Angle" , tidynames)
    tidynames <- gsub("gravity" , "Gravity" , tidynames)
    tidynames <- gsub("([\\.])" , "" , tidynames)
    tidynames <- gsub("mean" , "Mean" , tidynames)
    tidynames <- gsub("std" , "StandardDiviation" , tidynames)
    names(complete.activities) <- tidynames
    #print(names(complete.activities))
    write.table(complete.activities , "TidyData.txt" , row.names = FALSE)
}
